05-07-2012/Shouter/config/routes.rb
Shouter::Application.routes.draw do
  root to: "shouts#index"
  resources :shouts, only: [:index, :create]
  resources :users, only: [:create, :show]
  resource :session, only: [:create]
  get "sign_up" => "users#new"
  get "sign_in" => "sessions#new"
  delete "sign_out" => "sessions#destroy"
end

05-07-2012/Shouter/app/models/shout.rb
class Shout < ActiveRecord::Base
  belongs_to :user
  attr_accessible :body
  validates :body, presence: true

  def self.current
    order("created_at DESC")
  end
end

05-07-2012/Shouter/app/models/user.rb
class User < ActiveRecord::Base
  has_many :shouts
  attr_accessible :email
  validates :email, uniqueness: true, format: { with: /\A.+@.+\..+\z/ }
end

05-07-2012/Shouter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def current_user
    if cookies[:user_id]
      @current_user ||= User.find(cookies.signed[:user_id])
    end
  end
  helper_method :current_user

  def signed_in?
    current_user
  end
  helper_method :signed_in?

  def authorize
    if !signed_in?
      redirect_to new_session_url
    end
  end

  def sign_in(user)
    cookies.signed.permanent[:user_id] = user.id
  end
end

05-07-2012/Shouter/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user
      sign_in(user)
      redirect_to shouts_path, notice: "Signed in successfully"
    else
      redirect_to shouts_path, notice: "Could not sign you in"
    end
  end

  def destroy
    cookies.delete :user_id
    redirect_to shouts_path, notice: "Signed out"
  end
end

05-07-2012/Shouter/app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController
  before_filter :authorize, only: [:create]

  def index
    @shouts = Shout.current.paginate(page: params[:page], per_page: 10)
    @shout = Shout.new
  end

  def create
    @shout = current_user.shouts.new(params[:shout])
    if @shout.save
      redirect_to shouts_url, notice: "Shouted!"
    else
      @shouts = Shout.current
      render action: "index"
    end
  end
end

05-07-2012/Shouter/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @shouts = @user.shouts.paginate(page: params[:page], per_page: 10)
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in(@user)
      redirect_to shouts_url
    else
      render action: "new"
    end
  end
end

05-07-2012/Shouter/app/views/application/_flash.html.erb
<% if notice %>
  <p class='notice'><%= notice %></p>
<% end %>

05-07-2012/Shouter/app/views/application/_user_bar.html.erb
<% if signed_in? %>
  Welcome <%= current_user.email %>
  <%= link_to "Sign out", sign_out_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", sign_up_path %>
  <%= link_to "Sign in", sign_in_path %>
<% end %>

05-07-2012/Shouter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shouter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "user_bar" %>
<%= render "flash" %>

<%= yield %>

</body>
</html>

05-07-2012/Shouter/app/views/shouts/_form.html.erb
<%= form_for(shout) do |form| %>
  <% if shout.errors.any? %>
    <p>Shout couldn't be saved because:</p>
    <ul>
      <% shout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form.text_field :body, placeholder: "Shout here" %>
  <%= form.submit "Shout" %>
<% end %>

05-07-2012/Shouter/app/views/shouts/_shout.html.erb
<div>
  <%= link_to shout.user.email, shout.user %> says: <%= shout.body %> - <%= time_ago_in_words(shout.created_at) %> ago
</div>

05-07-2012/Shouter/app/views/shouts/index.html.erb
<% if signed_in? %>
  <%= render "form", shout: @shout %>
<% end %>

<%= render @shouts %>
<%= will_paginate @shouts %>

05-07-2012/Shouter/app/views/users/new.html.erb
<%= form_for(@user) do |form| %>
  <% if @user.errors.any? %>
    Could not sign you up because:
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form.email_field :email, placeholder: "you@example.com" %>
  <%= form.submit %>
<% end %>

05-07-2012/Shouter/app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<%= render @shouts %>
<%= will_paginate @shouts %>